"""Synthetic labeled examples for the intent classifier.

Each row is (text, intent_label). Six categories matching project.md §4.3.2 plus
'account_security' and 'promotion' that show up in the prototype mock data.
"""

INTENTS = [
    "Refund Request",
    "Delivery Issue",
    "Product Complaint",
    "Payment Failure",
    "Account / Security",
    "Promotion / Pricing",
    "Other",
]

EXAMPLES: list[tuple[str, str]] = [
    # ── Refund Request ─────────────────────────────────────────
    ("I want a refund for my damaged mug from order 12345.", "Refund Request"),
    ("Please refund my purchase, the item arrived broken.", "Refund Request"),
    ("Can I get my money back? The product is defective.", "Refund Request"),
    ("I'd like to return this and get a refund.", "Refund Request"),
    ("Refund please — the package arrived shattered.", "Refund Request"),
    ("How do I return a damaged item and get my money back?", "Refund Request"),
    ("Order 11234 had broken glassware, I want a refund.", "Refund Request"),
    ("I need a full refund for the defective headphones.", "Refund Request"),
    ("The mug set arrived smashed, requesting refund.", "Refund Request"),
    ("Charged me for an item that came broken — refund please.", "Refund Request"),
    ("Asking for a partial refund since one piece is cracked.", "Refund Request"),
    ("Item didn't match description, want money back.", "Refund Request"),
    ("Request to cancel order and refund the charge.", "Refund Request"),
    ("Refund my order asap, item is unusable.", "Refund Request"),
    ("Hi I'd like reimbursement for the broken vase.", "Refund Request"),
    ("Return shipped, when will my refund post?", "Refund Request"),
    ("Need a refund — the laptop stand is bent.", "Refund Request"),
    ("My headphones don't work, please refund.", "Refund Request"),
    ("Bought the hoodie last week, want to return for refund.", "Refund Request"),
    ("Refund requested for cracked plate set.", "Refund Request"),

    # ── Delivery Issue ────────────────────────────────────────
    ("Where is my package? It's been 9 days.", "Delivery Issue"),
    ("Tracking hasn't updated since Monday.", "Delivery Issue"),
    ("My order is late, FedEx tracking shows nothing.", "Delivery Issue"),
    ("Package has been stuck in transit for a week.", "Delivery Issue"),
    ("Estimated delivery was yesterday and it never came.", "Delivery Issue"),
    ("Order says delivered but I never received it.", "Delivery Issue"),
    ("Where's my shipment? Order 12290 hasn't arrived.", "Delivery Issue"),
    ("The courier left it at the wrong address.", "Delivery Issue"),
    ("I need to update my shipping address before it ships.", "Delivery Issue"),
    ("Tracking number is not working on the carrier site.", "Delivery Issue"),
    ("Has my package shipped yet? It's been 3 days.", "Delivery Issue"),
    ("Delivery is delayed, when will I get my order?", "Delivery Issue"),
    ("USPS shows the package is lost.", "Delivery Issue"),
    ("My order keeps getting rescheduled by the carrier.", "Delivery Issue"),
    ("I missed the delivery, how do I reschedule?", "Delivery Issue"),
    ("Package arrived to the neighbor by mistake.", "Delivery Issue"),
    ("I selected next-day shipping but it's been a week.", "Delivery Issue"),
    ("Why hasn't my parcel moved in 5 days?", "Delivery Issue"),
    ("Order shipped but no tracking info provided.", "Delivery Issue"),
    ("Delivery driver said no one was home but I was here.", "Delivery Issue"),

    # ── Product Complaint ─────────────────────────────────────
    ("The hoodie is the wrong size, I ordered medium got XL.", "Product Complaint"),
    ("Battery on the headphones dies in 6 hours, listing said 18.", "Product Complaint"),
    ("The color of the shirt is different from the photo.", "Product Complaint"),
    ("Quality of this product is way worse than expected.", "Product Complaint"),
    ("Fabric is itchy and feels cheap.", "Product Complaint"),
    ("This item doesn't work as described.", "Product Complaint"),
    ("The mug is smaller than advertised.", "Product Complaint"),
    ("Got the wrong item — ordered blue, got green.", "Product Complaint"),
    ("Product arrived but doesn't match the website.", "Product Complaint"),
    ("Headphones have buzzing sound out of the box.", "Product Complaint"),
    ("Stitching on the shirt is coming apart already.", "Product Complaint"),
    ("Wrong flavor delivered instead of mango.", "Product Complaint"),
    ("Sizing chart is misleading, doesn't fit at all.", "Product Complaint"),
    ("This isn't what I ordered, sent the wrong product.", "Product Complaint"),
    ("Material feels different from the description.", "Product Complaint"),
    ("Smaller than expected, photos are deceiving.", "Product Complaint"),
    ("Battery life is half what was advertised.", "Product Complaint"),
    ("Item works but very poor quality.", "Product Complaint"),
    ("The blanket is shedding fibers everywhere.", "Product Complaint"),
    ("Colors faded after one wash.", "Product Complaint"),

    # ── Payment Failure ───────────────────────────────────────
    ("I was charged twice for the same order.", "Payment Failure"),
    ("My card was declined but the money was still taken.", "Payment Failure"),
    ("Double charge on my credit card statement.", "Payment Failure"),
    ("Payment didn't go through but I got charged.", "Payment Failure"),
    ("The checkout failed but my bank shows a charge.", "Payment Failure"),
    ("I see two charges for the same purchase, please refund one.", "Payment Failure"),
    ("Why is there a duplicate transaction on my card?", "Payment Failure"),
    ("Card error at checkout but money was deducted.", "Payment Failure"),
    ("My PayPal was charged twice for order 12275.", "Payment Failure"),
    ("Got charged but order didn't go through.", "Payment Failure"),
    ("Pending charge that never cleared, what happened?", "Payment Failure"),
    ("Three pending authorizations on my card from your store.", "Payment Failure"),
    ("Payment was processed but no order confirmation.", "Payment Failure"),
    ("Billing issue — charged the wrong amount.", "Payment Failure"),
    ("The total charged doesn't match my invoice.", "Payment Failure"),
    ("Apple Pay said success but no order placed.", "Payment Failure"),

    # ── Account / Security ────────────────────────────────────
    ("There's a suspicious login from a device I don't recognize.", "Account / Security"),
    ("I can't log into my account, password reset isn't working.", "Account / Security"),
    ("Got an alert about a new login from another country.", "Account / Security"),
    ("My account was locked, how do I unlock it?", "Account / Security"),
    ("Someone may have hacked my account.", "Account / Security"),
    ("I'm locked out and the recovery email isn't arriving.", "Account / Security"),
    ("Two-factor codes are not coming through.", "Account / Security"),
    ("I think my account was compromised, please help.", "Account / Security"),
    ("Need to update my email on file.", "Account / Security"),
    ("Reset link in email expired before I clicked it.", "Account / Security"),
    ("Suspicious email pretending to be from your support.", "Account / Security"),
    ("Phishing attempt with my account info.", "Account / Security"),
    ("Account shows orders I never placed.", "Account / Security"),

    # ── Promotion / Pricing ───────────────────────────────────
    ("My coupon code WELCOME10 says expired but the email said tomorrow.", "Promotion / Pricing"),
    ("Discount code isn't being applied at checkout.", "Promotion / Pricing"),
    ("Promo code is invalid even though it should work.", "Promotion / Pricing"),
    ("The price changed between my cart and checkout.", "Promotion / Pricing"),
    ("Why is shipping suddenly more expensive?", "Promotion / Pricing"),
    ("Sale price didn't apply to my order.", "Promotion / Pricing"),
    ("Coupon SAVE20 not working on the bundle.", "Promotion / Pricing"),
    ("Item shows discounted price but charged full at checkout.", "Promotion / Pricing"),
    ("Loyalty discount not applied automatically.", "Promotion / Pricing"),
    ("I missed the sale by an hour, can I still get the price?", "Promotion / Pricing"),
    ("Why did the price increase since yesterday?", "Promotion / Pricing"),

    # ── Other / general ───────────────────────────────────────
    ("Do you have this in stock?", "Other"),
    ("What are your store hours?", "Other"),
    ("Just wanted to say I love the product!", "Other"),
    ("Where can I find the size guide?", "Other"),
    ("Can I gift wrap this?", "Other"),
    ("Do you ship to Canada?", "Other"),
    ("How do I leave a review?", "Other"),
    ("What's your return policy?", "Other"),
    ("Is there a warranty on this item?", "Other"),
]
